export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_APPLIES_SUCCESS = "GET_APPLIES_SUCCESS";
export const GET_BYID_APPLIES = "GET_BYID_APPLIES";
export const CREATE_APPLY_SUCCESS = "CREATE_APPLY_SUCCESS";
export const UPDATE_APPLY_SUCCESS = "UPDATE_APPLY_SUCCESS";
export const DELETE_APPLY_SUCCESS = "DELETE_APPLY_SUCCESS";
export const GET_BYID_APPLY = "GET_BYID_APPLY";

export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
export const GET_BY_DEPARTMENT_SUCCESS = "GET_BY_DEPARTMENT_SUCCESS";
export const CREATE_DEPARTMENT_SUCCESS = "CREATE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_SUCCESS= "ADD_DEPARTMENT_SUCCESS";

export const GET_TITLE_SUCCESS = "GET_TITLE_SUCCESS";
export const DELETE_TİTLE_SUCCESS = "DELETE_TİTLE_SUCCESS";
export const CREATE_CV_SUCCESS = "CREATE_CV_SUCCESS";
export const GET_CV_SUCCESS = "GET_CV_SUCCESS";
export const GET_BYCV_SUCCESS = "GET_BYCV_SUCCESS";