export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_APPLIES_SUCCESS = "GET_APPLIES_SUCCESS";

export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";

export const GET_TITLE_SUCCESS = "GET_TITLE_SUCCESS";