export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_APPLIES_SUCCESS = "GET_APPLIES_SUCCESS";
<<<<<<< HEAD
export const CREATE_CV_SUCCESS="CREATE_CV_SUCCESS";
=======

export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
>>>>>>> 3d1f3a182856f88b1ec46ff8e199e85bf9cbd51d
